config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root to: 'posts#index'

  get 'tops' => 'tops#index'
  get 'business' => 'tops#business'
  get 'cast' => 'tops#cast'
  get 'attract' => 'tops#attract'

  get 'contact' => 'contact#index'
  post 'confirm' =>'contact#confirm'
  post 'thanks' => 'contact#thanks'

  resources :posts do
    collection {post :import}
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :company, :name, :tel, :email, :address, :subject, :message

  validates :company, {presence: true}
  validates :name, {presence: true}
  validates :tel, {presence: true}
  validates :email, {presence: true}
  validates :address, {presence: true}
  validates :subject, {presence: true}
  validates :message, {presence: true}
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :file, ImagesUploader


  def to_meta_tags
    {
    	title: title,
    	keyword: keyword,
    	description: description
    }
  end

  @@Choicelists = [
        "和食・日本料理",
        "寿司・丼",
        "魚料理",
        "郷土料理",
        "イタリアン",
        "フレンチ",
        "トンカツ",
        "カレー",
        "中華",
        "アジア・エスニック",
        "焼肉・ステーキ",
        "焼鳥・串料理",
        "鍋・しゃぶしゃぶ・すき焼き",
        "居酒屋・バー",
        "カフェ・スイーツ",
        "その他"
  ]


  def self.Choicelists
    @@Choicelists
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      post = find_by(id: row['id']) || new
      post.attributes = row.to_hash.slice(*updatable_attributes)
      post.save!
    end
  end

  def self.updatable_attributes
    ["title", "file", "choice", "keyword", "description", "body", "store", "tel", "address", "genre", "bookking", "price_lunch", "price_dinner" , "payment" , "hours", "holiday", "evaluation", "csv_file"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
    render :action => "index"
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action =>  'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(contact_params)
    ContactMailer.received_email(@contact).deliver
  end

  private
  def contact_params
    params.require(:contact).permit(
    :company, #会社名
    :name,  #代表者名
    :tel, #電話番号
    :address, #住所
    :email, #メールアドレス
    :subject,
    :message
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_admin!, except: [:index, :show]

  def index
    @type = params[:type]
    @posts = Post.order(created_at: "DESC").page(params[:page]).per(20)
    case @type
    when "japanese" then
      @posts = Post.where(choice: "和食・日本料理").page(params[:page]).per(20)
    when "sushi" then
      @posts = Post.where(choice: "寿司・魚料理").page(params[:page]).per(20)
    when "italian" then
      @posts = Post.where(choice: "イタリアン").page(params[:page]).per(20)
    when "french" then
      @posts = Post.where(choice: "フレンチ").page(params[:page]).per(20)
    when "tonkatsu" then
      @posts = Post.where(choice: "トンカツ").page(params[:page]).per(20)
    when "curry" then
      @posts = Post.where(choice: "カレー").page(params[:page]).per(20)
    when "asia" then
      @posts = Post.where(choice: "アジア・エスニック").page(params[:page]).per(20)
    when "yakiniku" then
      @posts = Post.where(choice: "焼肉・ステーキ").page(params[:page]).per(20)
    when "yakitori" then
      @posts = Post.where(choice: "焼鳥・串料理").page(params[:page]).per(20)
    when "bar" then
      @posts = Post.where(choice: "居酒屋・バー").page(params[:page]).per(20)
    when "cafe" then
      @posts = Post.where(choice: "カフェ・スイーツ").page(params[:page]).per(20)
    when "other" then
      @posts = Post.where(choice: "その他").page(params[:page]).per(20)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
        redirect_to posts_path
    else
        render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    add_breadcrumb '記事編集', '/posts/edit'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
        redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
        redirect_to posts_path
    else
        render 'edit'
    end
  end

  def import
    Post.import(params[:csv_file])
    redirect_to posts_path, notice:"記事を追加しました"
  end

  private
    def post_params
        params.require(:post).permit(
        :title, #タイトル
        :file,  #写真
        :choice,  #カテゴリー
        :keyword, #キーワード
        :description, #説明
        :body, #本文
        :store, #店舗名
        :tel, #電話番号
        :address, #住所
        :genre, #ジャンル
        :bookking, #予約
        :price_lunch, #ランチ単価
        :price_dinner, #ディナー単価
        :payment, #支払方法
        :hours, #営業時間
        :holiday, #定休日
        :evaluation, #評価
        :csv_file
        )
    end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

  def cast
  end

  def attract
  end

  def company
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def default_meta_tags
    {
      title: "<%= yield(:title) || 'グルメライター奥山健太のオススメ店' %>" ,
      description: "年間300店舗の新規店舗を開拓するグルメライター奥山健太のオススメする優良店をジャンル別にご紹介",
      keywords:    "グルメライター",
	  canonical: request.original_url,  # 優先されるurl
      charset: "UTF-8",
      # OGPの設定をしておくとfacebook, twitterなどの投稿を見た目よくしてくれます。
    }
  end
  
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/contact/confirm.html.slim
= form_for(@contact, url: { action: :thanks }) do |f|
  .tops-wrapper
    h2.heading
      | お問い合わせ内容確認フォーム
    table.company
      colgroup
        col width="40%" /
        col width="60%" /
      tr
        th.arrow_box
          | 会社名
          strong.label.label-blue 必須
          br/
          small 株式会社ABC
        td
          = f.hidden_field :company
          = @contact.company
      tr
        th.arrow_box
          | 担当者名
          strong.label.label-blue 必須
          small 山田太郎
        td
          = f.hidden_field :name
          = @contact.name
      tr
        th.arrow_box
          | 電話番号
          strong.label.label-blue 必須
          small 00-0000-0000
        td
          = f.hidden_field :tel
          = @contact.tel
      tr
        th.arrow_box
          | メールアドレス
          strong.label.label-blue 必須
          small aaa@aaa.com
        td
          = f.hidden_field :email
          = @contact.email
      tr
        th.arrow_box
          | 住所
          strong.label.label-blue 必須
          small 東京都東京市東京町1-1-1
        td
          = f.hidden_field :address
          = @contact.address
      tr
        th.arrow_box
          | 住所
          strong.label.label-blue 必須
        td
          = f.hidden_field :subject
          = @contact.subject
      tr
        th.arrow_box
          | 本文
          strong.label.label-blue 必須
        td
          = f.hidden_field :message
          = @contact.message
      tr
        td colspan="2"
          = f.submit "送信"

app/views/contact/index.html.slim
= form_for(@contact, url: { action: :confirm }) do |f|
  - if @contact.errors.any?
    strong 入力内容にエラーがあります
    ul
      - @contact.errors.each do |attr, msg|
        li= msg

  .tops-wrapper
    h1.headline-first
      | お問い合わせフォーム
    br
    table.company
      colgroup
        col width="40%"
        col width="60%"
      tr
        th.arrow_box
          | 会社名
          strong.label.label-blue 必須
          small 株式会ABC
        td= f.text_field :company
      tr
        th.arrow_box
          | 担当者名
          strong.label.label-blue 必須
          small 山田太郎
        td= f.text_field :name
      tr
        th.arrow_box
          | 電話番号
          strong.label.label-blue 必須
          small 00-0000-0000
        td= f.text_field :tel
      tr
        th.arrow_box
          | メールアドレス
          strong.label.label-blue 必須
          small aaa@aaa.com
        td= f.email_field :email
      tr
        th.arrow_box
          | 住所
          strong.label.label-blue 必須
          small 東京都東京市東京町1-1-1
        td= f.text_field :address
      tr
        th.arrow_box
          | 件名
          strong.label.label-blue 必須
        td= f.select(:subject, [ \
            ["選択する","選択する"],      \
            ["掲載のご依頼","掲載のご依頼"],      \
            ["お仕事のご依頼","お仕事のご依頼"],      \
            ["その他","その他"]      \
            ])
      tr
        th.arrow_box
          | 本文
          strong.label.label-blue 必須
        td= f.text_area :message
      tr
        td colspan="2"
          = f.submit "確認"

app/views/contact/thanks.html.slim
.tops-wrapper.center
h1.headline  お問い合わせ頂きありがとうございました。

p
  | 確認後、担当者よりご連絡させて頂きます。
p
   = link_to "トップページへ戻る", "/"
br
br


script[async src="https://www.googletagmanager.com/gtag/js?id=AW-858090558"]
script
  |  window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-858090558');
script
  |  gtag('event', 'conversion', {'send_to': 'AW-858090558/NETyCM_wzKoBEL7YlZkD'});

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="uft-8"]
    meta[http-equiv="X^UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1,0, initial-scale=1, shrink-to-fit=no"]
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    script[src="https://ajax.googleapis.com/js/jquery-3.3.1/slim.min.js"]
    script[src="https://ajax.googleapis.com/js/bootstrap.bundle.min.js"]
    script[src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"]
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = display_meta_tags(default_meta_tags)
  .container-field
   header
    .row
     .col-xs-2
       = link_to "/" do
        = image_tag 'rogo.png' , class: "menu"
     .col-xs-2
      nav.globalMenuSp
       ul
         li
           = link_to "トップページ", "/"
       ul
         li
           = link_to "お問い合わせフォーム", "/contact"
     .col-xs-12.cp_ipselect.cp_sl05.right
      select[name="blood"]
       option[value=""]
         | 言語を選択
       option[value="japanese"]
         | 日本語
       option[value="korean"]
         | 韓国語
       option[value="chinese"]
         | 中国語
       option[value="english"]
         | 英語

   .navToggle
          span
          span
          span
          span menu
   br
   body
     p.notice = notice
     p.alert = alert
     = yield

app/views/posts/_form.html.slim
= form_for @post do |f|
   table.company
     tbody
      tr
        th.arrow_box タイトル
      tr
        td colspan="2" = text_field :post, :title, class:"title"
      tr
        th.arrow_box ファイル添付
      tr
        td  = f.file_field :file
      tr
        th.arrow_box カテゴリー選択
      tr
        td = f.select(:choice, Post.Choicelists)
      tr
        th.arrow_box  キーワード
      tr
        td = text_field :post, :keyword, class:"keyword"
      tr
        th.arrow_box  完結分（100文字以内）
      tr
        td = text_area :post, :description, class:"description"
      tr
        th.arrow_box 本文
      tr
        td = text_area :post, :body, class:"post-body"

   table.company
     tbody
      tr
        th 店舗名
        td = text_field :post, :store
        th 評価
        td = number_field :post, :evaluation
      tr
        th 電話番号
        td = phone_field :post, :tel
        th 住所
        td = text_field :post, :address
      tr
        th ジャンル
        td = text_field :post, :genre
        th 支払方法
        td = text_field :post, :payment
      tr
        th ランチ単価
        td = text_field :post, :price_lunch
        th ディナー単価
        td = text_field :post, :price_dinner
      tr
        th 営業時間
        td = text_field :post, :hours
        th 定休日
        td = text_field :post, :holiday
      tr
        th[colspan="2"] 予約方法
        td[colspan="2"] = text_area :post, :bookking
      tr
        td[colspan="4"] = f.submit '投稿する'

app/views/posts/edit.html.slim
- set_meta_tags noindex: true

.tops-wrapper
	h2.headline-first  記事編集
	br
	= form_for @post do |f|
	   table.company
	     tbody
	      tr
	        th.arrow_box タイトル
	      tr
	        td colspan="2" = text_field :post, :title, class:"title"
	      tr
	        th.arrow_box ファイル添付
	      tr
	        td  = f.file_field :file
	      tr
	        th.arrow_box カテゴリー選択
	      tr
	        td = f.select(:choice, Post.Choicelists)
	      tr
	        th.arrow_box  キーワード
	      tr
	        td = text_field :post, :keyword, class:"keyword"
	      tr
	        th.arrow_box  完結分（100文字以内）
	      tr
	        td = text_area :post, :description, class:"description"
	      tr
	        th.arrow_box 本文
	      tr
	        td = text_area :post, :body, class:"post-body"

	   table.company
	     tbody
	      tr
	        th 店舗名
	        td = text_field :post, :store
	        th 評価
	        td = number_field :post, :evaluation
	      tr
	        th 電話番号
	        td = phone_field :post, :tel
	        th 住所
	        td = text_field :post, :address
	      tr
	        th ジャンル
	        td = text_field :post, :genre
	        th 支払方法
	        td = text_field :post, :payment
	      tr
	        th ランチ単価
	        td = text_field :post, :price_lunch
	        th ディナー単価
	        td = text_field :post, :price_dinner
	      tr
	        th 営業時間
	        td = text_field :post, :hours
	        th 定休日
	        td = text_field :post, :holiday
	      tr
	        th[colspan="2"] 予約方法
	        td[colspan="2"] = text_area :post, :bookking
	      tr
	        td[colspan="4"] = f.submit '投稿する'

app/views/posts/index.html.slim
- set_meta_tags  title: '絶対外さないお店選びならeatery-japan|eaterist_kenta'
- set_meta_tags  keyword: '東京 美味しい,おすすめ グルメ'
- set_meta_tags  description: '美味しいお店を1000件以上食べ歩いて来たeaterist_kentaがオススメする絶対外さない東京グルメを出し惜しみなしご紹介！'

.tops-wrapper
  .row
    .col-sm-8
      h1.headline
        | 新着記事
      - @posts.each do |post|
        .row
          .col-sm-5
            = image_tag post.file.to_s, width:"100%", class:"post-space"
          .col-sm-7.post-base
            .post-title
              = link_to post.title, post_path(post)
            .post-description
              = post.description.html_safe
            - if admin_signed_in?
                = link_to '編集  ', edit_post_path(post), class: 'command'
                = link_to '  削除',
                 			            	post_path(post),
                 			            	method: :delete,
                 			            	class: 'command',
                 			            	data: { confirm: '本当に削除しますか？'}
        br
        hr
      = paginate @posts
    .col-sm-4
      .row
        .col-sm-12
          h2.headline
            | カテゴリー一覧
          = link_to '和食・日本料理', posts_path(type: "japanese", post: '[desc]'), class:"square_btn"
          = link_to '寿司・丼', posts_path(type: "sushi", post: '[desc]'), class:"square_btn"
          = link_to 'イタリアン', posts_path(type: "italian", post: '[desc]'), class:"square_btn"
          = link_to 'フレンチ', posts_path(type: "french", post: '[desc]'), class:"square_btn"
          = link_to 'とんかつ', posts_path(type: "tonkatsu", post: '[desc]'), class:"square_btn"
          = link_to 'カレー', posts_path(type: "administrative", post: '[desc]'), class:"square_btn"
          = link_to 'アジア・エスニック', posts_path(type: "asia", post: '[desc]'), class:"square_btn"
          = link_to '焼肉・ステーキ', posts_path(type: "yakiniku", post: '[desc]'), class:"square_btn"
          = link_to '焼鳥・串料理', posts_path(type: "yakitori", post: '[desc]'), class:"square_btn"
          = link_to '居酒屋・バー', posts_path(type: "bar", post: '[desc]'), class:"square_btn"
          = link_to 'カフェ・スイーツ', posts_path(type: "cafe", post: '[desc]'), class:"square_btn"
          = link_to 'その他', posts_path(type: "other", post: '[desc]'), class:"square_btn"

app/views/posts/new.html.slim
- set_meta_tags noindex: true

.tops-wrapper
br
  h2.headline  新着記事作成
  == render 'form'

app/views/posts/show.html.slim
- set_meta_tags  title: '助成金・補助金をどこよりも詳しく知るなら｜SMART Documentカテゴリー一覧'
- set_meta_tags  keyword: '助成金 詳細,補助金 詳細'
- set_meta_tags  description: '助成金・補助金の記事をどこよりも詳しく知るならSMART Document'

#post-detail.tops-wrapper
  .fr-view
	  h1.headline-first  = @post.title
       - if @post.file?
      .image_post  = image_tag @post.file.url
	  p  = @post.body.html_safe

table.company
 col[width="40%"]
 col[width="60%"]
 tr
  th[colspan="2"] 店舗情報
 tr
  th 店舗名
  td =@post.store
 tr
  th 評価点数
  td =@post.evaluation
 tr
  th 電話番号
  td =@post.tel
 tr
  th 住所
  td =@post.address
 tr
  th ジャンル
  td =@post.genre
 tr
  th 予約方法
  td =@post.bookking
 tr
  th 予算（昼）
  td =@post.price_lunch
 tr
  th 予算（夜）
  td =@post.price_dinner
 tr
  th 支払方法
  td =@post.payment
 tr
  th 営業時間
  td =@post.hours
 tr
  th 定休日
  td =@post.holiday
 tr
  th 最終更新日
  td =@post.created_at

br
br
br

app/views/tops/cast.html.slim
- set_meta_tags  title: 'インフルエンサーとして一緒に飲食店を宣伝しませんか？|グルメ専門のキャスティング会社ならeatery'
- set_meta_tags  keyword: 'グルメ キャスティング,グルメ　インフルエンサー,キャスティング　インフルエンサー'
- set_meta_tags  description: 'グルメ専門のキャスティング会社ならeatery。食通のあなたがインフルエンサーとして輝ける環境を提供します。あなたを待っている飲食店はたくさんあります。'

br
br
/#トップ
br
.back-image.back-image-app
  .row
    .col-xs-1
    .col-xs-7.face-1
        |  グルメ専門のインフルエンサーキャスティング会社
        br
        |  あなたの拡散性と趣味が職業へ！
        br
          .face-2
            |  『eaterist大募集中』
            br
              .face-price
                |  １アポ
                strong
                   | 15,000
                | 円~
              .box2
                p
                  | 平均アポ獲得率５％
              .face-price
                |
                strong
                  |
                  |
                  |

    .col-xs-4.visible-md.visible-lg
        .box1
          p
            | 毎月5名様限定受付

br
hr.line
br


/# Trouble
.top-wrapper
  h2.heading
    strong
      | eateristって何？
    |
  br
  br
  h6.heading
    | レストランのことを海外では別名で『eatery』と呼ばれます。弊社では、それを宣伝して頂くインフルエンサーの方々をeateristと呼んでいます。eateryとマッチングしたeateristのマッチングを弊社ではお手伝いしているキャスティング会社となります。
  br
  br
  .row.center
    .col-sm-4
     = image_tag "restaurant.jpg", width:"100%"
     h4 1.eatery(レストラン)
    .col-sm-4
     = image_tag "match.gif", width:"100%"
    .col-sm-4
     = image_tag "shot.jpg", width:"100%"
     h4 2.eaterist(投稿者)
    br


br
hr.line
br


/# Trouble
.top-wrapper
  h2.heading
    strong
      | eateristってどんなことするの？
  br
  br
  h6.heading
    | 拡散を希望する店舗より弊社に依頼が入ります。eateristはそのお店に訪問し、感想をSNSに発信して頂きます。発信を行なって頂くと、弊社より報酬をお支払いします。
  br
  br
  .row.center
    .col-sm-4.padding
     = image_tag "picture.jpg", width:"100%"
     p 1.写真を撮影
    .col-sm-4.padding
     = image_tag "post.jpg", width:"100%"
     p 2.投稿・レビュー
    .col-sm-4.padding
     = image_tag "application.jpg", width:"100%"
     p 3.弊社に申請



br
hr.line
br


.top-wrapper
  h2.heading
    strong
      |  eateristになれる人は？
  br
  br
  h6.heading
    | eateristは独自のセグメント方式を設け、全てのインフルエンサーが認められる訳ではなく、グルメに精通している人だけが登録することが出来ます。
  br
  br
  .row.center
    .col-sm-1
    .col-sm-4
     = image_tag "sns.jpg", width:"100%"
     p 1.SNSやブログに投稿している
    .col-sm-2
    .col-sm-4
     = image_tag "eat.jpg", width:"100%"
     p 2.グルメに特化した記事を書いている
    .col-sm-1


br
hr.line
br

/# push font
h2.push
   span
     | 【eateristになるメリットをご紹介】

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      |  誰でも簡単に始められる
  br
  br
  .row
   .col-sm-7
     p.middle
      | eateristには実績や投稿内容、拡散力を基準として５つのランクに分けられます。お店の方もこの実績を見て判断するため収入アップにも繋がります。
   .col-sm-4
     = image_tag "smartphone.jpg", width:"100%"
   .col-sm-1

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      | 良質な内容はeatery-japanで世界発信
  br
  br
  .row
   .col-sm-7
     p.middle
      | eateristの良質な評価は当社が運営する海外向け拡散サイトeatery-japanへ掲載されます。
   .col-sm-4
     = image_tag "rogo2.png", width:"100%"
   .col-sm-1

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      | レセプションパーティーにも参加出来る
  br
  br
  .row
   .col-sm-7
     p.middle
      | eateristの良質な評価は当社が運営する海外向け拡散サイトeatery-japanへ掲載されます。
   .col-sm-4
     = image_tag "reception.jpg", width:"100%"
   .col-sm-1

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      | 定期的なグルメ会の開催
  br
  br
  .row
   .col-sm-7
     p.middle
      | eateristの良質な評価は当社が運営する海外向け拡散サイトeatery-japanへ掲載されます。
   .col-sm-4
     = image_tag "event.jpg", width:"100%"
   .col-sm-1

br
hr.line
br



.top-wrapper
  h2.heading
    strong
      |  eateristになるまでの流れ
  br
  br
  h6.heading
    | eateryに登録頂き、案件取得から報酬確定迄の流れの概要をご案内いたします。
  br
  br
  .row.center
    .col-sm-4.padding
     = image_tag "sns.jpg", width:"100%"
     p 1.以下申込フォームより申請を行います
    .col-sm-4.padding
     = image_tag "wait.jpg", width:"100%"
     p 2.eateryにて審査を行いますので承認をお待ち下さい
    .col-sm-4.padding
     = image_tag "phone.jpg", width:"100%"
     p 3.通過後、訪問したい案件に申請を行います
  br
  br
  .row.center
    .col-sm-4.padding
     = image_tag "eating.jpg", width:"100%"
     p 4.店舗から承認があれば日程調整後に訪問して下さい
    .col-sm-4.padding
     = image_tag "eat.jpg", width:"100%"
     p 5.レビューを書いてeateryへ申請を上げます
    .col-sm-4.padding
     = image_tag "application.jpg", width:"100%"
     p 6.月末締め翌月末で報酬発生の場合お振込致します

br
hr.line
br


.row
  .col-sm-12.center
    =link_to "/contact", :target=>["_blank"]   do
      =image_tag 'question.gif', width: '50%', class: 'center'

br
hr.line
br